# Generated by Django 4.2.6 on 2023-10-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='boody',
            new_name='body',
        ),
    ]
